name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the default branch of your repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Copy everything from the client folder to the root of the gh-pages branch
      - name: Deploy client folder to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client  # Path to your client folder that contains index.html
